# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    container_name: nginx_burdujasergiu
    build:
      context: .
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm

  php-fpm:
    container_name: php_burdujasergiu
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb_burdujasergiu
    image: mariadb:11.0.3  # Replace with the desired MariaDB version
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root       # Root password
      MYSQL_DATABASE: burdujasergiu        # Database name
    volumes:
      - "./docker/mysql:/var/lib/mysql"
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    ports:
      - "33062:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_burdujasergiu
    restart: always
    ports:
     - '8084:80'
    environment:
      MAX_EXECUTION_TIME: 600
      UPLOAD_LIMIT: 800M
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root # server mysql, user root, password root
    depends_on:
     - mariadb

  # node:
  #   build:
  #     context: .
  #     dockerfile: docker/node/node.docker
  #   container_name: node
  #   volumes:
  #     - ./:/var/www
  #   tty: true
